PREFIX dc:   <http://purl.org/dc/terms/>
PREFIX geom: <http://geovocab.org/geometry#>
PREFIX lgdo: <http://linkedgeodata.org/ontology/>
PREFIX ogcgs:  <http://www.opengis.net/ont/geosparql#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX todo: <http://todo/>

SELECT 
  ?bikerack
  ?wkt
  ?contributor
  ?modified
  ?access  
  ?type
  ?capacity
  ?covered
  ?parking
  ?description
  ?label
  ?area
  ?streetName

WHERE { 
  ?bikerack 
    a lgdo:BicycleParking ;
    ?has ?geometry .

  ?geometry ogcgs:asWKT ?wkt .

  OPTIONAL { ?bikerack  dc:contributor ?contributor } .
  OPTIONAL { ?bikerack  dc:modified ?modified } .
  OPTIONAL { ?bikerack  lgdo:access ?access } .
  OPTIONAL { ?bikerack  lgdo:bicycle_parking ?type } .
  OPTIONAL { ?bikerack  lgdo:capacity ?capacity } .
  OPTIONAL { ?bikerack  lgdo:covered ?covered } .
  OPTIONAL { ?bikerack  lgdo:parking ?parking } .
  OPTIONAL { ?bikerack  rdfs:comment ?description } .
  OPTIONAL { ?bikerack  rdfs:label ?label } .
  OPTIONAL { ?bikerack  todo:area ?area } .
  OPTIONAL { ?bikerack  lgdo:near _:street .
             _:street   a lgdo:HighwayThing ;
                        rdfs:label ?streetName .
  }
}
